---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datagen-app-deployment
spec:
  selector:
    matchLabels:
      app: datagen-app
  template:
    metadata:
      labels:
        app: datagen-app
      annotations:
        dapr.io/enabled: 'true'
        dapr.io/app-id: datagen-app
        dapr.io/config: dapr-go-crud-app
        dapr.io/log-as-json: 'true'
    spec:
      containers:
      - name: datagen-app
        image: ghcr.io/andriykalashnykov/dapr-go-crud-app/datagen:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - name: tmp
        emptyDir: {}
