---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: errorgen-app-deployment
spec:
  selector:
    matchLabels:
      app: errorgen-app
  template:
    metadata:
      labels:
        app: errorgen-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "errorgen-app"
        dapr.io/config: dapr-crud-app
        dapr.io/log-as-json: "true"
    spec:
      containers:
      - name: errorgen-app
        image: andriykalashnykov/errorgen-4c58529a678401f7741de37538be0187:latest
        imagePullPolicy: Always