---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher-app
  template:
    metadata:
      labels:
        app: publisher-app
      annotations:
        dapr.io/enabled: 'true'
        dapr.io/app-id: publisher-app
        dapr.io/app-port: '8080'
        dapr.io/config: dapr-go-crud-app
        dapr.io/app-protocol: grpc
        dapr.io/log-as-json: 'true'
    spec:
      containers:
      - name: app
        image: andriykalashnykov/publisher-3630a7760c9fdeddb1d57b5700d97918:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 6
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - name: tmp
        emptyDir: {}
